name: Deploy to Nginx

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Configure NPM
        run: npm config set legacy-peer-deps true

      - name: Install Ionic
        run: npm install -g @ionic/cli

      - name: Install dependencies
        run: npm install

      - name: Build
        run: ionic build --prod

      - name: Upload application to NGINX
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          source: "www"
          target: "/var/www/html/"
